name: Java test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Run tests
        run: mvn -B test


#The on section specifies that the action will run on pushes and pull requests to the main branch.
#The workflow_dispatch event allows you to manually trigger the workflow from the GitHub Actions tab in your GitHub repository.
#The steps section defines the individual steps of the job:
#The first step checks out the repository code.
#The second step sets up the Java Development Kit (JDK) using the actions/setup-java action.
#The third step runs the Maven command to execute the tests.